"""
generate_synthetic_users.py
============================
GratiFlow Phase 1 Evaluation — Synthetic User Generation

IMPORTANT: All user entries generated by this script are SYNTHETIC (LLM-generated).
           No real participants are involved. This is a proof-of-concept evaluation only.

Model: gpt-5.4-mini (OpenAI Chat Completions API)
  - max_completion_tokens is used (max_tokens is NOT supported by this model)
  - temperature is NOT sent (not supported by gpt-5.4-mini)
  - seed=2026 is used for reproducibility (best-effort; API does not guarantee determinism)

Output:
  data/processed/experiments/synthetic_user_prompts.json  — all prompts used for generation
  data/processed/experiments/synthetic_user_entries.json  — generated journal entries
  data/raw/synthetic_users_raw_responses.json             — raw API responses (do NOT edit)

Author: team member (experiment lead, the research team)
Date: 2026-06-04
"""

import json
import os
import time
import random
import hashlib
from datetime import datetime, timezone
from pathlib import Path

import requests

# ── Constants ─────────────────────────────────────────────────────────────────

SYNTHETIC_USER_SEED = 2026
EXPERIMENT_SEED = 42
MODEL = "gpt-5.4-mini"
MAX_COMPLETION_TOKENS = 512  # journal entries are short; 512 is sufficient
API_URL = "https://api.openai.com/v1/chat/completions"

# Retry settings
MAX_RETRIES = 3
RETRY_WAIT_BASE = 2.0  # seconds (exponential backoff base)

# Paths
BASE_DIR = Path(__file__).parent.parent
DATA_PROCESSED = BASE_DIR / "data" / "processed" / "experiments"
DATA_RAW = BASE_DIR / "data" / "raw"
PERSONAS_FILE = Path(__file__).parent / "personas.json"

# ── Reframe stage → instruction mapping ─────────────────────────────────────

REFRAME_INSTRUCTIONS = {
    "none": (
        "Do NOT include any spontaneous positive reframing of negative events. "
        "The student simply describes what happened without reinterpreting negatives."
    ),
    "partial": (
        "Include ONE attempt at reframing a negative event, but make it partial or uncertain "
        "(e.g., 'もしかしたら…かもしれない' or 'まあ…と思えばいいのかも'). "
        "The reframe should feel tentative, not confident."
    ),
    "clear": (
        "Include 1 clear, confident positive reframing of a negative event "
        "(e.g., 'これはむしろ良い機会だったと思う'). The reframe should be explicitly stated."
    ),
    "clear2": (
        "Include 1-2 clear, confident positive reframings of negative events. "
        "The student naturally and confidently reinterprets challenges as opportunities for growth."
    ),
}

# ── Load API key ─────────────────────────────────────────────────────────────

def load_api_key() -> str:
    """Load OpenAI API key from .env. Never log or output the key."""
    env_path = Path(".env")
    if not env_path.exists():
        raise FileNotFoundError(f".env not found. Create a .env file with OPENAI_API_KEY=your_key")
    with open(env_path) as f:
        for line in f:
            line = line.strip()
            if line.startswith("OPENAI_API_KEY="):
                key = line.split("=", 1)[1].strip().strip('"').strip("'")
                if key:
                    return key
    raise ValueError("OPENAI_API_KEY not found. Create a .env file with OPENAI_API_KEY=your_key")


# ── Build prompt for a single session ────────────────────────────────────────

def build_generation_prompt(
    persona: dict,
    session_config: dict,
    previous_summary: str,
) -> tuple[str, str]:
    """
    Build the system prompt and user message for synthetic journal generation.

    Returns:
        (system_prompt, user_message): strings to pass to the API
    """
    reframe_instruction = REFRAME_INSTRUCTIONS[session_config["reframe_stage"]]
    neg_count = session_config["neg_count"]
    session_num = session_config["session"]

    system_prompt = (
        "You are a simulation engine generating synthetic university student journal entries "
        "for a research experiment. These entries are SYNTHETIC and do not represent any real person. "
        "Generate realistic-sounding Japanese journal entries that match the given persona and session parameters exactly."
    )

    user_message = f"""You are simulating a university student writing a daily gratitude journal.

Persona: {persona['label']} — {persona['description']}
Session number: {session_num} of 10
Current skill trajectory: {persona['trajectory']}
Previous sessions summary: {previous_summary}

Generate a journal entry (3-5 sentences in Japanese) that includes:
- 1-3 positive events from today
- {neg_count} negative events or negative framings
- {reframe_instruction}

The entry should feel natural, like a real student's daily reflection.
Output ONLY the journal entry text in Japanese. Do not include any explanation or meta-text."""

    return system_prompt, user_message


# ── OpenAI API call with retry ────────────────────────────────────────────────

def call_openai(
    api_key: str,
    system_prompt: str,
    user_message: str,
    seed: int = SYNTHETIC_USER_SEED,
    retries: int = MAX_RETRIES,
) -> dict:
    """
    Call gpt-5.4-mini with retry and exponential backoff.

    Notes:
      - max_completion_tokens is used (max_tokens not supported)
      - temperature is NOT sent (not supported by gpt-5.4-mini)
      - seed is passed for best-effort reproducibility
    """
    headers = {
        "Content-Type": "application/json",
        "Authorization": f"Bearer {api_key}",
    }
    payload = {
        "model": MODEL,
        "messages": [
            {"role": "system", "content": system_prompt},
            {"role": "user", "content": user_message},
        ],
        "max_completion_tokens": MAX_COMPLETION_TOKENS,
        "seed": seed,
    }

    for attempt in range(1, retries + 1):
        try:
            resp = requests.post(API_URL, headers=headers, json=payload, timeout=60)
            resp.raise_for_status()
            return resp.json()
        except requests.exceptions.HTTPError as e:
            status = e.response.status_code if e.response else None
            if status == 429 or (status and status >= 500):
                wait = RETRY_WAIT_BASE ** attempt
                print(f"    [retry {attempt}/{retries}] HTTP {status}, waiting {wait:.1f}s...")
                time.sleep(wait)
            else:
                raise
        except requests.exceptions.RequestException as e:
            wait = RETRY_WAIT_BASE ** attempt
            print(f"    [retry {attempt}/{retries}] Request error: {e}, waiting {wait:.1f}s...")
            time.sleep(wait)
    raise RuntimeError(f"API call failed after {retries} retries")


# ── Main generation loop ──────────────────────────────────────────────────────

def generate_all_entries(api_key: str) -> tuple[list, list, list]:
    """
    Generate all 50 synthetic journal entries (5 personas x 10 sessions).

    Returns:
        (all_prompts, all_entries, raw_responses)
    """
    random.seed(EXPERIMENT_SEED)

    with open(PERSONAS_FILE) as f:
        persona_data = json.load(f)

    personas = persona_data["personas"]
    all_prompts = []
    all_entries = []
    raw_responses = []

    total = sum(len(p["sessions"]) for p in personas)
    count = 0

    for persona in personas:
        previous_summary = "This is the first session. No previous sessions."
        persona_entries = []

        for session_config in persona["sessions"]:
            count += 1
            session_num = session_config["session"]
            print(f"  [{count}/{total}] {persona['id']} Session {session_num} "
                  f"(neg={session_config['neg_count']}, reframe={session_config['reframe_stage']})...")

            system_prompt, user_message = build_generation_prompt(
                persona, session_config, previous_summary
            )

            # Record the prompt (for transparency and reproducibility)
            prompt_record = {
                "persona_id": persona["id"],
                "session": session_num,
                "system_prompt": system_prompt,
                "user_message": user_message,
                "parameters": {
                    "neg_count": session_config["neg_count"],
                    "reframe_stage": session_config["reframe_stage"],
                    "seed": SYNTHETIC_USER_SEED,
                    "model": MODEL,
                    "max_completion_tokens": MAX_COMPLETION_TOKENS,
                },
                "note": "SYNTHETIC: This prompt was used to generate a simulated journal entry. No real user is involved.",
            }
            all_prompts.append(prompt_record)

            # Call the API
            raw_resp = call_openai(api_key, system_prompt, user_message)
            raw_responses.append({
                "persona_id": persona["id"],
                "session": session_num,
                "raw_response": raw_resp,
            })

            # Extract generated text
            entry_text = raw_resp["choices"][0]["message"]["content"].strip()

            # Create brief summary for next session context
            pos_words = ["感謝", "嬉しい", "楽しい", "成長", "充実", "達成", "前向き"]
            neg_words = ["不安", "失敗", "辛い", "疲れ", "難しい", "ストレス"]
            has_pos = any(w in entry_text for w in pos_words)
            has_neg = any(w in entry_text for w in neg_words)
            previous_summary = (
                f"Session {session_num}: "
                + ("Positive expressions detected. " if has_pos else "")
                + ("Negative expressions detected. " if has_neg else "")
                + (f"Reframing stage: {session_config['reframe_stage']}.")
            )

            entry_record = {
                "persona_id": persona["id"],
                "session": session_num,
                "user_entry": entry_text,
                "generation_params": {
                    "neg_count": session_config["neg_count"],
                    "reframe_stage": session_config["reframe_stage"],
                    "expected_scaffold": session_config["expected_scaffold"],
                },
                "synthetic": True,
                "model_used": MODEL,
                "seed": SYNTHETIC_USER_SEED,
                "note": (
                    "SYNTHETIC USER ENTRY: This text was generated by an LLM to simulate "
                    "a university student's gratitude journal. It does not represent any real person."
                ),
            }
            all_entries.append(entry_record)
            persona_entries.append(entry_record)

            # Brief pause to avoid rate limiting
            time.sleep(0.5)

    return all_prompts, all_entries, raw_responses


# ── Save outputs ──────────────────────────────────────────────────────────────

def save_outputs(all_prompts: list, all_entries: list, raw_responses: list) -> None:
    """Save all outputs to the appropriate directories."""
    DATA_PROCESSED.mkdir(parents=True, exist_ok=True)
    DATA_RAW.mkdir(parents=True, exist_ok=True)

    timestamp = datetime.now(timezone.utc).isoformat()

    # Save prompts (for transparency)
    prompts_path = DATA_PROCESSED / "synthetic_user_prompts.json"
    with open(prompts_path, "w", encoding="utf-8") as f:
        json.dump({
            "meta": {
                "description": "All prompts used to generate synthetic user journal entries for GratiFlow evaluation.",
                "note": "SYNTHETIC USERS: No real participants. Generated by gpt-5.4-mini.",
                "generated_at": timestamp,
                "model": MODEL,
                "seed": SYNTHETIC_USER_SEED,
                "total_prompts": len(all_prompts),
            },
            "prompts": all_prompts,
        }, f, ensure_ascii=False, indent=2)
    print(f"  Saved: {prompts_path}")

    # Save entries (clean version for experiment pipeline)
    entries_path = DATA_PROCESSED / "synthetic_user_entries.json"
    with open(entries_path, "w", encoding="utf-8") as f:
        json.dump({
            "meta": {
                "description": "Synthetic user journal entries for GratiFlow Phase 1 evaluation.",
                "note": (
                    "SYNTHETIC USERS (N=5 personas x 10 sessions = 50 entries). "
                    "All entries are LLM-generated by gpt-5.4-mini. "
                    "No real participants are involved in this study."
                ),
                "generated_at": timestamp,
                "model": MODEL,
                "seed": SYNTHETIC_USER_SEED,
                "total_entries": len(all_entries),
            },
            "entries": all_entries,
        }, f, ensure_ascii=False, indent=2)
    print(f"  Saved: {entries_path}")

    # Save raw responses (immutable raw data)
    raw_path = DATA_RAW / "synthetic_users_raw_responses.json"
    with open(raw_path, "w", encoding="utf-8") as f:
        json.dump({
            "meta": {
                "description": "Raw OpenAI API responses for synthetic user generation. DO NOT EDIT.",
                "generated_at": timestamp,
                "model": MODEL,
            },
            "responses": raw_responses,
        }, f, ensure_ascii=False, indent=2)
    print(f"  Saved (raw, do not edit): {raw_path}")


# ── Entry point ───────────────────────────────────────────────────────────────

def main() -> None:
    print("=" * 60)
    print("GratiFlow Synthetic User Generation")
    print("IMPORTANT: All generated entries are SYNTHETIC (LLM-generated).")
    print("No real participants are involved.")
    print(f"Model: {MODEL} | Seed: {SYNTHETIC_USER_SEED}")
    print("=" * 60)

    print("\nLoading API key...")
    api_key = load_api_key()
    # Do not log the key value
    print("  API key loaded successfully.")

    print("\nGenerating 50 synthetic journal entries (5 personas x 10 sessions)...")
    start_time = time.time()
    all_prompts, all_entries, raw_responses = generate_all_entries(api_key)
    elapsed = time.time() - start_time

    print(f"\nGeneration complete: {len(all_entries)} entries in {elapsed:.1f}s")

    print("\nSaving outputs...")
    save_outputs(all_prompts, all_entries, raw_responses)

    print("\nDone. Review data/processed/experiments/synthetic_user_prompts.json")
    print("before running experiments (as requested by the research team-sensei).")


if __name__ == "__main__":
    main()
