"""
srr_human_validation_llm_judge.py
===================================
Blind LLM judgment (gpt-5.4-mini) for SRR single-annotator validation.

IMPORTANT: This script MUST be run BEFORE the PI completes annotation,
and its output (llm_labels_blind.csv) MUST NOT be shared with the PI
until all 70 PI labels have been filled in.

Data source: Ziems et al. (2022) Positive Psychology Frames (CC BY-SA 4.0)
  https://aclanthology.org/2022.acl-long.257/

Model: gpt-5.4-mini (OpenAI) — PI-specified judge model for GratiFlow framework
  - Uses max_completion_tokens=1024 (no temperature parameter)
  - Rate-limit aware: retry with exponential backoff
  - API key: loaded from .env (NEVER printed to stdout)

NOTE: Previous run used gpt-4o-mini (incorrect). This version corrects the
model to gpt-5.4-mini per PI instruction (2026-06-06).

Output:
  data/processed/srr_human_validation/llm_labels_blind.csv
    Columns: id, llm_srr_label, llm_reasoning

Author: team member (experiment lead, the research team)
Date: 2026-06-06 (re-run with corrected model gpt-5.4-mini)
"""

import csv
import json
import os
import re
import time
import random
from pathlib import Path

from openai import OpenAI

# ─── Paths ─────────────────────────────────────────────────────────────────────
BASE = Path(__file__).resolve().parent.parent
BLANK_CSV = os.path.join(BASE, "data/processed/srr_human_validation/annotation_sheet_blank.csv")
OUT_CSV   = os.path.join(BASE, "data/processed/srr_human_validation/llm_labels_blind.csv")
LOG_JSON  = os.path.join(BASE, "data/processed/srr_human_validation/llm_judge_log.json")

API_KEY_FILE = os.path.expanduser(".env")
MODEL = "gpt-5.4-mini"
MAX_COMPLETION_TOKENS = 1024

# ─── Load API key ──────────────────────────────────────────────────────────────
def load_api_key() -> str:
    """Load OPENAI_API_KEY from .env. Never prints the key."""
    with open(API_KEY_FILE, encoding="utf-8") as f:
        for line in f:
            line = line.strip()
            if line.startswith("OPENAI_API_KEY="):
                return line.split("=", 1)[1].strip()
    raise ValueError("OPENAI_API_KEY not found. Create a .env file with OPENAI_API_KEY=your_key")

# ─── SRR Rubric system prompt (v2.1 affect rubric, paired/context-aware mode) ──
SYSTEM_PROMPT = """You are the Affect-Analysis Agent in GratiFlow, operating in paired/context-aware mode.
Your task is to judge whether a candidate text constitutes a Spontaneous Reframing Response (SRR)
given the original negative context.

You will receive a JSON object with two fields:
  "context": the original negative statement or tweet (source of negative emotion)
  "candidate_text": the text to be judged

Respond with ONLY valid JSON (no markdown fences, no extra text).

Required JSON schema:
{
  "srr": <integer, 1 if SRR, 0 if not SRR>,
  "reasoning": "<string, 1-2 sentence justification citing which criteria (R1/R2/R3/F1-F5) apply>"
}

=== RUBRIC: Spontaneous Reframing Response (SRR) ===

Definition (from cognitive reappraisal theory; Gross, 1998):
SRR = 1 if and only if the candidate_text satisfies ALL THREE of:
  (R1) An explicitly stated or clearly implied negative event or emotion is present
       (typically derived from the context).
  (R2) A deliberate reinterpretation that transforms the meaning of that SAME negative event
       into a positive, growth-oriented, or silver-lining perspective.
  (R3) Evidence that the reframe is generated by the speaker themselves, not echoed from
       an external prompt or prior AI instruction.

SRR = 0 if any of the following apply:
  (F1) The candidate describes a positive event that is SEPARATE from the negative context
       — no reinterpretation of the negative event itself.
       Example: Context = deadline stress; Candidate = "had fun with friends at cafe" → F1.
  (F2) The candidate expresses vague optimism or a coping platitude without specific
       cognitive reinterpretation of the negative event.
       Example: "that's life" / "it'll work out somehow" / "nothing I can do" → F2.
  (F3) The reframe directly repeats or paraphrases language modeled by an AI in a prior message.
  (F4) The positive content exists only because of a direct prompt instruction;
       no self-generated cognitive shift is evident.
  (F5) The candidate only describes negative events/emotions with no positive reinterpretation.

=== FEW-SHOT EXAMPLES ===

--- Example 1: SRR = 1 (clear reframe) ---
Input: {
  "context": "Studied and made notecards all night, uhhhh hate finals and keystones at the same time. Not a Happy Camper",
  "candidate_text": "I studied and took notes all night, I'm working hard and that's good."
}
Output: {"srr": 1, "reasoning": "R1: studying all night under exam stress (negative); R2: reframes the same effort as inherently positive ('working hard and that's good'); R3: self-generated perspective. All three criteria met."}

--- Example 2: SRR = 1 (tentative reframe) ---
Input: {
  "context": "can guarantee I will cry at least once before Friday I'm so far behind in my nursing readings",
  "candidate_text": "I fell behind my nursing readings, but I know it's my own fault, now I have to power through all of it, I can do it!"
}
Output: {"srr": 1, "reasoning": "R1: falling behind on readings (negative); R2: acknowledges fault and reframes as a self-efficacy challenge ('I can do it!'); R3: self-generated determination, no AI echo. All three criteria met."}

--- Example 3: SRR = 0 — F5 (negative only) ---
Input: {
  "context": "I need a day just to finish all my projects and graduation stuff.",
  "candidate_text": "I need a day just to finish all my projects and graduation stuff. justoneday stressed"
}
Output: {"srr": 0, "reasoning": "F5: candidate only describes the negative situation (stress about projects) with no reinterpretation. R2 not met."}

--- Example 4: SRR = 0 — F2 (vague acceptance / neutralizing) ---
Input: {
  "context": "I want to lay down and die.., Just wake up at a time when society isn't such a load of bullshit.",
  "candidate_text": "I wanted to lay down, and wake up at a time when society isn't so bad. But that's life, and I should be enjoying the good parts of it."
}
Output: {"srr": 0, "reasoning": "F2: 'that's life and I should be enjoying the good parts' is a coping platitude without specific cognitive reinterpretation of the negative event. R2 not met — no positive meaning is actively constructed from the stated negative."}

--- Example 5: SRR = 0 — F1 (separate positive event) ---
Input: {
  "context": "Project project project~~ Y cnt teacher assign us earlier. Made us really rush hard!",
  "candidate_text": "Teachers ought to give more time to students for project work. This would result in a smooth and timely completion of projects."
}
Output: {"srr": 0, "reasoning": "F1/F2: candidate expresses a policy preference rather than reinterpreting the past negative event (rush stress). No transformation of meaning of the negative experience. R2 not met."}

--- Example 6: SRR = 0 — F5 (negative only with self-comparison) ---
Input: {
  "context": "When people are involved in more things than I am I always wonder how they do it.",
  "candidate_text": "When people are involved in more things than I am I always wonder how they do it."
}
Output: {"srr": 0, "reasoning": "F5: pure expression of self-doubt and comparison. No reinterpretation of the negative feeling. R2 not met."}

=== END RUBRIC ===

Rules:
- Always return valid JSON with exactly two fields: 'srr' (integer 0 or 1) and 'reasoning' (string).
- When context is empty or missing, judge based on candidate_text alone.
- When in doubt, assign srr = 0. All three criteria (R1, R2, R3) must be clearly evidenced.
- Do NOT infer intent beyond what is explicitly written.
"""

def make_user_message(context: str, candidate_text: str) -> str:
    payload = {"context": context, "candidate_text": candidate_text}
    return json.dumps(payload, ensure_ascii=False)

def call_llm_with_retry(client: OpenAI, context: str, candidate_text: str,
                         item_id: str, max_retries: int = 5) -> dict:
    """
    Call gpt-5.4-mini with the SRR rubric. Retries on rate-limit / transient errors.
    Returns dict with keys: srr (int), reasoning (str).
    """
    for attempt in range(1, max_retries + 1):
        try:
            response = client.chat.completions.create(
                model=MODEL,
                messages=[
                    {"role": "system", "content": SYSTEM_PROMPT},
                    {"role": "user",   "content": make_user_message(context, candidate_text)},
                ],
                max_completion_tokens=MAX_COMPLETION_TOKENS,
                # temperature is intentionally omitted (use model default)
            )
            raw_text = response.choices[0].message.content.strip()

            # Parse JSON response
            parsed = json.loads(raw_text)
            srr_val = int(parsed.get("srr", -1))
            if srr_val not in (0, 1):
                raise ValueError(f"Invalid srr value: {srr_val}")
            reasoning = str(parsed.get("reasoning", "")).strip()

            return {
                "srr": srr_val,
                "reasoning": reasoning,
                "raw_response": raw_text,
                "usage": {
                    "prompt_tokens": response.usage.prompt_tokens,
                    "completion_tokens": response.usage.completion_tokens,
                },
            }

        except Exception as e:
            wait = 2 ** attempt + random.uniform(0, 1)
            print(f"  [WARN] {item_id} attempt {attempt}/{max_retries} failed: {e}. "
                  f"Retrying in {wait:.1f}s...")
            if attempt == max_retries:
                print(f"  [ERROR] {item_id} exhausted retries. Assigning srr=0 with error note.")
                return {
                    "srr": 0,
                    "reasoning": f"[ERROR: LLM call failed after {max_retries} retries: {e}]",
                    "raw_response": "",
                    "usage": {},
                }
            time.sleep(wait)

# ─── Main ──────────────────────────────────────────────────────────────────────
def main():
    print("=" * 60)
    print("SRR Blind LLM Judgment — gpt-5.4-mini")
    print("Data: Ziems et al. (2022) CC BY-SA 4.0")
    print("NOTE: Corrected model from gpt-4o-mini to gpt-5.4-mini (2026-06-06)")
    print("=" * 60)

    # Load annotation sheet
    with open(BLANK_CSV, newline="", encoding="utf-8") as f:
        items = list(csv.DictReader(f))
    print(f"Loaded {len(items)} items from annotation_sheet_blank.csv")

    # Initialize OpenAI client (key loaded from file, never printed)
    api_key = load_api_key()
    client = OpenAI(api_key=api_key)

    results = []
    log_entries = []
    total_tokens = {"prompt": 0, "completion": 0}

    for i, item in enumerate(items, 1):
        item_id = item["id"]
        context = item["context"]
        candidate_text = item["candidate_text"]

        print(f"[{i:2d}/70] Judging {item_id} ...", end=" ", flush=True)

        result = call_llm_with_retry(client, context, candidate_text, item_id)

        print(f"srr={result['srr']}")

        results.append({
            "id": item_id,
            "llm_srr_label": result["srr"],
            "llm_reasoning": result["reasoning"],
        })

        log_entries.append({
            "id": item_id,
            "context": context,
            "candidate_text": candidate_text,
            "llm_srr_label": result["srr"],
            "llm_reasoning": result["reasoning"],
            "raw_response": result["raw_response"],
            "usage": result["usage"],
        })

        if result["usage"]:
            total_tokens["prompt"]     += result["usage"].get("prompt_tokens", 0)
            total_tokens["completion"] += result["usage"].get("completion_tokens", 0)

        # Polite rate-limit buffer (1 req/s ≈ safe for gpt-5.4-mini tier-1)
        if i < len(items):
            time.sleep(1.0)

    # Save blind labels CSV (shared with PI after annotation)
    with open(OUT_CSV, "w", newline="", encoding="utf-8") as f:
        writer = csv.DictWriter(f, fieldnames=["id", "llm_srr_label", "llm_reasoning"])
        writer.writeheader()
        writer.writerows(results)
    print(f"\n[saved] {OUT_CSV}")

    # Save full log JSON (internal use)
    log = {
        "description": (
            "Blind LLM judgment log for SRR single-annotator validation. "
            "Model: gpt-5.4-mini (corrected from gpt-4o-mini on 2026-06-06 per PI instruction). "
            "DO NOT share llm_srr_label distribution with PI before annotation is complete."
        ),
        "data_source": {
            "dataset": "SALT-NLP/positive_reframing",
            "paper": "Ziems et al. (2022), ACL 2022",
            "license": "CC BY-SA 4.0",
            "url": "https://aclanthology.org/2022.acl-long.257/",
        },
        "model": MODEL,
        "max_completion_tokens": MAX_COMPLETION_TOKENS,
        "total_items": len(results),
        "total_tokens": total_tokens,
        "rubric_basis": "evaluation_protocol_v2_1.md (the research team, 2026-06-04)",
        "entries": log_entries,
    }
    with open(LOG_JSON, "w", encoding="utf-8") as f:
        json.dump(log, f, ensure_ascii=False, indent=2)
    print(f"[saved] {LOG_JSON}  (full log with raw responses — internal only)")

    print(f"\nTotal tokens used: prompt={total_tokens['prompt']}, "
          f"completion={total_tokens['completion']}")
    print("\nBlind judgment complete. Do NOT reveal label distribution to PI before annotation.")


if __name__ == "__main__":
    main()
