"""
srr_realdata_validation.py
==========================
GratiFlow SRR Rubric Classifier — Validation on Real Human Data
(Positive Psychology Frames, Ziems et al., ACL 2022)

Dataset: SALT-NLP/positive_reframing (CC BY-SA 4.0)
  Ziems, C., Li, M., Zhang, A., & Yang, D. (2022).
  Inducing Positive Perspectives with Text Reframing.
  ACL 2022, 3682-3700. https://aclanthology.org/2022.acl-long.257/

Attribution: This validation uses data from the above dataset under CC BY-SA 4.0.
  Original data is NOT modified; only sampled for evaluation.

Purpose:
  Validates that the GratiFlow Affect-Analysis Agent SRR rubric (R1-R3, F1-F5)
  correctly detects spontaneous reframing vs. non-reframing in real human-written
  English text. This replaces the synthetic-only (acc=1.0) validation with
  genuine discriminative validity evidence.

Positive (SRR=1 equivalent):
  reframed_text where strategy in {growth, self_affirmation, optimism, thankfulness}
  → Human-written genuine cognitive reframe

Negative (SRR=0 equivalent):
  original_text  → Raw negative tweet (no reframe attempt; F4/F5 category)
  reframed_text where strategy in {neutralizing, impermanence}
  → Hard negative: ambiguous/mild reframe that may not meet R1-R3 threshold

Sample: 150 positive + 150 negative = 300 total (seed=42, cost control)

LLM: gpt-5.4-mini
API key: .env (OPENAI_API_KEY, never logged or output)
Protocol: max_completion_tokens=256, no temperature parameter, retry with backoff

Author: team member (experiment lead, the research team)
Date: 2026-06-05
"""

import json
import random
import sys
import time
from collections import Counter, defaultdict
from datetime import datetime, timezone
from pathlib import Path
from typing import Optional

import matplotlib
import matplotlib.patches as mpatches
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import requests
import seaborn as sns
from datasets import load_dataset

# ── Reproducibility ────────────────────────────────────────────────────────────
SEED = 42
random.seed(SEED)
np.random.seed(SEED)

# ── Model / API settings ───────────────────────────────────────────────────────
MODEL = "gpt-5.4-mini"
API_URL = "https://api.openai.com/v1/chat/completions"
MAX_COMPLETION_TOKENS = 256   # SRR rubric needs only spontaneous_reframe + reasoning
MAX_RETRIES = 3
RETRY_WAIT_BASE = 2.0

# ── Sampling parameters ────────────────────────────────────────────────────────
N_POSITIVE = 150   # reframed_text with strong reframe strategies
N_NEGATIVE_HARD = 75   # reframed_text with neutralizing/impermanence (hard negative)
N_NEGATIVE_EASY = 75   # original_text (raw negative tweets, easy negative)
N_TOTAL = N_POSITIVE + N_NEGATIVE_HARD + N_NEGATIVE_EASY  # 300

POSITIVE_STRATEGIES = {"growth", "self_affirmation", "optimism", "thankfulness"}
HARD_NEG_STRATEGIES = {"neutralizing", "impermanence"}

# ── Paths ──────────────────────────────────────────────────────────────────────
BASE_DIR = Path(__file__).parent.parent
RAW_DIR = BASE_DIR / "data" / "raw" / "srr_realdata_ziems2022"
PROCESSED_DIR = BASE_DIR / "data" / "processed" / "srr_realdata_validation"
EVAL_DIR = BASE_DIR / "evaluation" / "srr_realdata_validation"
PAPER_FIG_DIR = (
    BASE_DIR
    / "paper"
    / "en"
    / "GratiFlow__A_Scaffolding_Fading_Multi_Agent_LLM_for_Positive_Reframing_Skill_Development"
    / "figures"
)

for d in [RAW_DIR, PROCESSED_DIR, EVAL_DIR, PAPER_FIG_DIR]:
    d.mkdir(parents=True, exist_ok=True)

# ── SRR Rubric Prompt (same Affect-Analysis Agent as production) ───────────────
# NOTE: Using a stripped-down version that asks only for spontaneous_reframe
# and srr_reasoning (minimizes tokens, consistent rubric logic).
SRR_JUDGE_SYSTEM_PROMPT = (
    "You are the Affect-Analysis Agent in GratiFlow. "
    "Your task is to judge whether a given text contains a 'spontaneous reframe'.\n\n"
    "Respond with ONLY valid JSON (no markdown fences):\n"
    '{"spontaneous_reframe": <boolean>, "srr_reasoning": "<1-2 sentences>"}\n\n'
    "=== RUBRIC: spontaneous_reframe judgment ===\n\n"
    "Definition (operationalized from cognitive reappraisal theory):\n"
    "A 'spontaneous reframe' is TRUE if and only if the user's text contains ALL THREE of:\n"
    "  (R1) An explicitly stated negative event or negative emotion (the source).\n"
    "  (R2) A deliberate reinterpretation that transforms the meaning of that SAME negative event\n"
    "       into a positive, growth-oriented, or silver-lining perspective (the reframe).\n"
    "  (R3) Evidence that the reframe was generated by the user THEMSELVES, not echoed from\n"
    "       a prior AI response or from a prompt instruction.\n\n"
    "spontaneous_reframe is FALSE if any of the following apply:\n"
    "  (F1) The user simply describes a positive event without connecting it to a negative one.\n"
    "  (F2) The user expresses vague optimism or a coping platitude without specific reinterpretation.\n"
    "  (F3) The user repeats or paraphrases a reframe that the AI previously modeled for them.\n"
    "  (F4) The user only describes the negative event without any positive reinterpretation.\n"
    "  (F5) The positive aspect is about a DIFFERENT event, not a reinterpretation of the negative one.\n\n"
    "=== FEW-SHOT EXAMPLES ===\n\n"
    '--- Example 1: TRUE ---\n'
    'Entry: "My presentation totally bombed today. But thinking about it, the failure showed me exactly '
    "where I'm underprepared. Now I know what to work on. The failure became a lesson.\"\n"
    '{"spontaneous_reframe": true, "srr_reasoning": "R1: presentation failure. R2: reinterprets as revealing '
    'preparation gaps. R3: self-generated insight with action plan."}\n\n'
    '--- Example 2: TRUE (tentative) ---\n'
    'Entry: "My boss criticized me harshly at work. It stings, but maybe she said it because she expects more '
    'from me than from others."\n'
    '{"spontaneous_reframe": true, "srr_reasoning": "R1: harsh criticism. R2: tentative reinterpretation as '
    "sign of high expectations. R3: self-generated ('maybe'). Tentative but genuine cognitive shift.\"}\n\n"
    '--- Example 3: FALSE (F5 - separate positive event) ---\n'
    'Entry: "I had a stressful day with the deadline. But I had a nice lunch with friends."\n'
    '{"spontaneous_reframe": false, "srr_reasoning": "The positive event (lunch) is entirely separate from '
    'the negative one (deadline). F5: positive aspect about a different event."}\n\n'
    '--- Example 4: FALSE (F2 - vague optimism) ---\n'
    'Entry: "The experiment failed. Well, things will somehow work out."\n'
    '{"spontaneous_reframe": false, "srr_reasoning": "Vague optimism without reinterpreting the failure. '
    "F2: coping platitude without specific cognitive shift.\"}\n\n"
    '--- Example 5: FALSE (F4 - negative only) ---\n'
    'Entry: "I felt terrible all day. Could not focus on anything."\n'
    '{"spontaneous_reframe": false, "srr_reasoning": "No positive reinterpretation present. F4: negative '
    'description only."}\n\n'
    "=== END RUBRIC ===\n\n"
    "Rules:\n"
    "- Apply the rubric strictly. When in doubt, mark spontaneous_reframe as FALSE.\n"
    "- R1, R2, R3 must ALL be met for TRUE.\n"
    "- Do NOT infer intent beyond what is explicitly written."
)


# ── Utilities ──────────────────────────────────────────────────────────────────

def load_api_key() -> str:
    """Load API key from .env. Never log or output the key."""
    env_path = Path(".env")
    with open(env_path) as f:
        for line in f:
            line = line.strip()
            if line.startswith("OPENAI_API_KEY="):
                key = line.split("=", 1)[1].strip().strip('"').strip("'")
                if key:
                    return key
    raise ValueError("OPENAI_API_KEY not found. Create a .env file with OPENAI_API_KEY=your_key")


def call_srr_judge(api_key: str, text: str, item_id: str) -> dict:
    """
    Call gpt-5.4-mini with SRR rubric prompt for a single text.
    Returns dict with spontaneous_reframe (bool or None) and srr_reasoning.
    """
    messages = [
        {"role": "system", "content": SRR_JUDGE_SYSTEM_PROMPT},
        {"role": "user", "content": text},
    ]
    payload = {
        "model": MODEL,
        "messages": messages,
        "max_completion_tokens": MAX_COMPLETION_TOKENS,
    }
    headers = {
        "Content-Type": "application/json",
        "Authorization": f"Bearer {api_key}",
    }

    for attempt in range(1, MAX_RETRIES + 1):
        try:
            resp = requests.post(API_URL, headers=headers, json=payload, timeout=60)
            resp.raise_for_status()
            data = resp.json()
            content = data["choices"][0]["message"]["content"].strip()
            # Parse JSON
            cleaned = content
            if cleaned.startswith("```"):
                lines = cleaned.split("\n")
                cleaned = "\n".join(lines[1:-1]) if len(lines) > 2 else cleaned
            parsed = json.loads(cleaned)
            return {
                "spontaneous_reframe": bool(parsed.get("spontaneous_reframe", False)),
                "srr_reasoning": parsed.get("srr_reasoning", ""),
                "error": None,
            }
        except requests.exceptions.HTTPError as e:
            status = e.response.status_code if e.response else None
            if status == 429 or (status and status >= 500):
                wait = RETRY_WAIT_BASE ** attempt
                print(f"    [{item_id}] retry {attempt}/{MAX_RETRIES} HTTP {status}, wait {wait:.1f}s")
                time.sleep(wait)
            else:
                err_text = e.response.text[:200] if e.response else str(e)
                return {"spontaneous_reframe": None, "srr_reasoning": "", "error": f"HTTP {status}: {err_text}"}
        except (json.JSONDecodeError, KeyError) as e:
            if attempt < MAX_RETRIES:
                time.sleep(RETRY_WAIT_BASE)
            else:
                return {"spontaneous_reframe": None, "srr_reasoning": "", "error": f"ParseError: {e}"}
        except Exception as e:
            wait = RETRY_WAIT_BASE ** attempt
            print(f"    [{item_id}] retry {attempt}/{MAX_RETRIES} Error: {e}, wait {wait:.1f}s")
            time.sleep(wait)

    return {"spontaneous_reframe": None, "srr_reasoning": "", "error": f"Failed after {MAX_RETRIES} retries"}


# ── Data preparation ───────────────────────────────────────────────────────────

def parse_strategy_field(strategy_val) -> list:
    """
    The dataset's 'strategy' field can be:
      - A string like "['growth', 'optimism']"  (list-formatted string)
      - A plain string like "growth"
      - A list already parsed
      - Garbage (e.g., "[Wrong!] stressed...")
    Returns a list of strategy strings, or empty list if unparseable.
    """
    if isinstance(strategy_val, list):
        return [str(s).strip().strip("'\"") for s in strategy_val]
    if not isinstance(strategy_val, str):
        return []
    s = strategy_val.strip()
    if s.startswith("[") and s.endswith("]"):
        # Attempt ast.literal_eval for list-like strings
        try:
            import ast
            parsed = ast.literal_eval(s)
            if isinstance(parsed, list):
                return [str(x).strip().strip("'\"") for x in parsed]
        except Exception:
            pass
        return []
    # Plain single strategy string
    clean = s.strip("'\"")
    if clean in (
        "growth", "optimism", "self_affirmation", "thankfulness",
        "neutralizing", "impermanence",
    ):
        return [clean]
    return []


def prepare_sample(ds_train) -> pd.DataFrame:
    """
    Sample 150 positive + 75 hard-negative + 75 easy-negative from the dataset.

    The 'strategy' field is a multi-label list string, e.g. "['growth', 'optimism']".
    We parse it and assign rows by whether they contain ANY positive strategy vs.
    ONLY negative strategies.

    Positive: reframed_text where parsed strategies contain at least one from POSITIVE_STRATEGIES
    Hard-neg: reframed_text where parsed strategies are ALL from HARD_NEG_STRATEGIES (none from POSITIVE_STRATEGIES)
    Easy-neg: original_text (raw negative tweets, deduplicated)

    Returns a DataFrame with columns:
        item_id, text, gold_label (bool), sample_type, strategy_raw,
        strategy_parsed, original_text_ref
    """
    import ast

    df = pd.DataFrame(ds_train)
    print(f"\nFull dataset: {len(df)} rows")

    # Parse strategy field
    df["strategy_parsed"] = df["strategy"].apply(parse_strategy_field)
    df["strategy_raw"] = df["strategy"]

    # Filter out rows with unparseable strategy
    df = df[df["strategy_parsed"].apply(len) > 0].reset_index(drop=True)
    print(f"Rows with parseable strategy: {len(df)}")

    # Count individual strategy occurrences
    all_strategies = []
    for strats in df["strategy_parsed"]:
        all_strategies.extend(strats)
    print("Individual strategy occurrences (from parsed):")
    for strat, cnt in sorted(Counter(all_strategies).items()):
        print(f"  {strat}: {cnt}")

    rng = random.Random(SEED)

    # ── Positive: contains at least one POSITIVE_STRATEGY ─────────────────
    def has_positive(strats):
        return bool(set(strats) & POSITIVE_STRATEGIES)

    def is_hard_negative(strats):
        # All strategies are from HARD_NEG_STRATEGIES only
        return (
            len(strats) > 0
            and set(strats).issubset(HARD_NEG_STRATEGIES)
            and not (set(strats) & POSITIVE_STRATEGIES)
        )

    pos_pool = df[df["strategy_parsed"].apply(has_positive)].copy()
    hard_pool = df[df["strategy_parsed"].apply(is_hard_negative)].copy()

    print(f"\nPositive pool (has POSITIVE_STRATEGIES): {len(pos_pool)} rows")
    print(f"Hard-neg pool (HARD_NEG_STRATEGIES only): {len(hard_pool)} rows")

    if len(pos_pool) < N_POSITIVE:
        raise ValueError(f"Insufficient positive pool: {len(pos_pool)} < {N_POSITIVE}")
    if len(hard_pool) < N_NEGATIVE_HARD:
        print(f"  WARNING: hard_pool {len(hard_pool)} < {N_NEGATIVE_HARD}, using all available.")
        N_HARD_ACTUAL = len(hard_pool)
    else:
        N_HARD_ACTUAL = N_NEGATIVE_HARD

    pos_sample = pos_pool.sample(n=N_POSITIVE, random_state=SEED)
    hard_sample = hard_pool.sample(n=N_HARD_ACTUAL, random_state=SEED)

    # Assign primary strategy label for reporting (first POSITIVE_STRATEGY found)
    def primary_strategy_positive(strats):
        for s in ["growth", "self_affirmation", "optimism", "thankfulness"]:
            if s in strats:
                return s
        return strats[0] if strats else "unknown"

    def primary_strategy_negative(strats):
        for s in ["neutralizing", "impermanence"]:
            if s in strats:
                return s
        return strats[0] if strats else "unknown"

    pos_records = []
    for _, row in pos_sample.iterrows():
        pos_records.append({
            "item_id": f"POS_{len(pos_records):04d}",
            "text": row["reframed_text"],
            "gold_label": True,
            "sample_type": "positive",
            "strategy": primary_strategy_positive(row["strategy_parsed"]),
            "strategy_raw": row["strategy_raw"],
            "original_text_ref": row["original_text"],
        })

    hard_records = []
    for _, row in hard_sample.iterrows():
        hard_records.append({
            "item_id": f"HNEG_{len(hard_records):04d}",
            "text": row["reframed_text"],
            "gold_label": False,
            "sample_type": "hard_negative",
            "strategy": primary_strategy_negative(row["strategy_parsed"]),
            "strategy_raw": row["strategy_raw"],
            "original_text_ref": row["original_text"],
        })

    # ── Easy-negative: original_text (raw negative tweets) ───────────────
    easy_pool = df.drop_duplicates(subset=["original_text"]).copy()
    easy_sample = easy_pool.sample(n=N_NEGATIVE_EASY, random_state=SEED)
    easy_records = []
    for _, row in easy_sample.iterrows():
        easy_records.append({
            "item_id": f"ENEG_{len(easy_records):04d}",
            "text": row["original_text"],
            "gold_label": False,
            "sample_type": "easy_negative",
            "strategy": primary_strategy_negative(row["strategy_parsed"])
                if not has_positive(row["strategy_parsed"])
                else primary_strategy_positive(row["strategy_parsed"]),
            "strategy_raw": row["strategy_raw"],
            "original_text_ref": row["original_text"],
        })

    all_records = pos_records + hard_records + easy_records
    rng.shuffle(all_records)

    sample_df = pd.DataFrame(all_records)
    print(f"\nSample prepared: {len(sample_df)} items")
    print(f"  Positive (gold=True): {sample_df['gold_label'].sum()}")
    print(f"  Negative (gold=False): {(~sample_df['gold_label']).sum()}")
    print(f"  Hard-neg: {(sample_df['sample_type']=='hard_negative').sum()}")
    print(f"  Easy-neg: {(sample_df['sample_type']=='easy_negative').sum()}")

    return sample_df


# ── Main experiment loop ───────────────────────────────────────────────────────

def run_experiment(api_key: str, sample_df: pd.DataFrame) -> pd.DataFrame:
    """
    Apply SRR rubric judge to each sampled text.
    Returns sample_df with added columns: predicted_label, srr_reasoning_llm, error_flag.
    """
    predicted_labels = []
    srr_reasonings = []
    error_flags = []

    total = len(sample_df)
    print(f"\nRunning SRR judge on {total} items (model: {MODEL})...")

    for i, (idx, row) in enumerate(sample_df.iterrows()):
        item_id = row["item_id"]
        text = row["text"]
        gold = row["gold_label"]

        if (i + 1) % 10 == 0 or i == 0:
            print(f"  [{i+1}/{total}] {item_id} | gold={gold} | type={row['sample_type']}")

        result = call_srr_judge(api_key, text, item_id)
        time.sleep(0.4)  # Rate control: ~2.5 req/s

        predicted_labels.append(result["spontaneous_reframe"])
        srr_reasonings.append(result["srr_reasoning"])
        error_flags.append(result["error"] is not None)

        if result["error"]:
            print(f"    [ERROR] {item_id}: {result['error']}")

    sample_df = sample_df.copy()
    sample_df["predicted_label"] = predicted_labels
    sample_df["srr_reasoning_llm"] = srr_reasonings
    sample_df["error_flag"] = error_flags

    return sample_df


# ── Metrics computation ────────────────────────────────────────────────────────

def compute_metrics(results_df: pd.DataFrame) -> dict:
    """
    Compute accuracy, precision, recall, F1, confusion matrix.
    Excludes rows with API errors (predicted_label=None).
    """
    valid = results_df[results_df["predicted_label"].notna()].copy()
    valid["predicted_label"] = valid["predicted_label"].astype(bool)
    valid["gold_label"] = valid["gold_label"].astype(bool)

    n_errors = len(results_df) - len(valid)

    tp = int(((valid["gold_label"] == True) & (valid["predicted_label"] == True)).sum())
    fp = int(((valid["gold_label"] == False) & (valid["predicted_label"] == True)).sum())
    tn = int(((valid["gold_label"] == False) & (valid["predicted_label"] == False)).sum())
    fn = int(((valid["gold_label"] == True) & (valid["predicted_label"] == False)).sum())

    total = tp + fp + tn + fn
    accuracy = (tp + tn) / total if total > 0 else 0.0
    precision = tp / (tp + fp) if (tp + fp) > 0 else 0.0
    recall = tp / (tp + fn) if (tp + fn) > 0 else 0.0
    f1 = (2 * precision * recall / (precision + recall)) if (precision + recall) > 0 else 0.0

    # ── Strategy-level breakdown ───────────────────────────────────────────
    strategy_breakdown = {}
    for strat in sorted(valid["strategy"].unique()):
        strat_df = valid[valid["strategy"] == strat]
        strat_gold_pos = strat_df[strat_df["gold_label"] == True]
        strat_gold_neg = strat_df[strat_df["gold_label"] == False]

        s_tp = int(((strat_df["gold_label"] == True) & (strat_df["predicted_label"] == True)).sum())
        s_fp = int(((strat_df["gold_label"] == False) & (strat_df["predicted_label"] == True)).sum())
        s_tn = int(((strat_df["gold_label"] == False) & (strat_df["predicted_label"] == False)).sum())
        s_fn = int(((strat_df["gold_label"] == True) & (strat_df["predicted_label"] == False)).sum())

        s_total = s_tp + s_fp + s_tn + s_fn
        s_acc = (s_tp + s_tn) / s_total if s_total > 0 else float("nan")
        s_prec = s_tp / (s_tp + s_fp) if (s_tp + s_fp) > 0 else float("nan")
        s_rec = s_tp / (s_tp + s_fn) if (s_tp + s_fn) > 0 else float("nan")
        s_f1 = (2 * s_prec * s_rec / (s_prec + s_rec)) if (s_prec + s_rec) > 0 and not (
            np.isnan(s_prec) or np.isnan(s_rec)) else float("nan")

        # For negative strategies, recall is always NaN — use FPR instead
        is_positive_strategy = strat in POSITIVE_STRATEGIES
        strategy_breakdown[strat] = {
            "n": s_total,
            "n_gold_positive": len(strat_gold_pos),
            "n_gold_negative": len(strat_gold_neg),
            "gold_label": "positive" if is_positive_strategy else "negative",
            "tp": s_tp, "fp": s_fp, "tn": s_tn, "fn": s_fn,
            "accuracy": round(s_acc, 4) if not np.isnan(s_acc) else None,
            "precision": round(s_prec, 4) if not np.isnan(s_prec) else None,
            "recall_or_detection_rate": round(s_rec, 4) if not np.isnan(s_rec) else None,
            "f1": round(s_f1, 4) if not np.isnan(s_f1) else None,
            # For negatives: false positive rate = fp / (fp+tn)
            "false_positive_rate": round(s_fp / (s_fp + s_tn), 4) if (s_fp + s_tn) > 0 else None,
        }

    # ── Sample type breakdown ──────────────────────────────────────────────
    type_breakdown = {}
    for stype in ["positive", "hard_negative", "easy_negative"]:
        sub = valid[valid["sample_type"] == stype]
        if len(sub) == 0:
            continue
        sub_gold = sub["gold_label"].values
        sub_pred = sub["predicted_label"].values
        correct = (sub_gold == sub_pred).sum()
        fp_sub = int(((sub_gold == False) & (sub_pred == True)).sum())
        fn_sub = int(((sub_gold == True) & (sub_pred == False)).sum())
        type_breakdown[stype] = {
            "n": len(sub),
            "correct": int(correct),
            "accuracy": round(correct / len(sub), 4),
            "fp": fp_sub,
            "fn": fn_sub,
        }

    return {
        "n_total": total,
        "n_valid": len(valid),
        "n_errors": n_errors,
        "tp": tp, "fp": fp, "tn": tn, "fn": fn,
        "accuracy": round(accuracy, 4),
        "precision": round(precision, 4),
        "recall": round(recall, 4),
        "f1": round(f1, 4),
        "strategy_breakdown": strategy_breakdown,
        "sample_type_breakdown": type_breakdown,
    }


# ── Error analysis ─────────────────────────────────────────────────────────────

def analyze_errors(results_df: pd.DataFrame) -> dict:
    """
    Identify systematic error patterns.
    Returns dict with false positive and false negative examples.
    """
    valid = results_df[results_df["predicted_label"].notna()].copy()
    valid["predicted_label"] = valid["predicted_label"].astype(bool)
    valid["gold_label"] = valid["gold_label"].astype(bool)

    false_positives = valid[(valid["gold_label"] == False) & (valid["predicted_label"] == True)]
    false_negatives = valid[(valid["gold_label"] == True) & (valid["predicted_label"] == False)]

    def sample_errors(df, n=5):
        return [
            {
                "item_id": row["item_id"],
                "sample_type": row["sample_type"],
                "strategy": row["strategy"],
                "text": row["text"][:300],
                "srr_reasoning_llm": row["srr_reasoning_llm"],
            }
            for _, row in df.head(n).iterrows()
        ]

    # FP breakdown by sample type
    fp_by_type = Counter(false_positives["sample_type"].tolist())
    fn_by_type = Counter(false_negatives["sample_type"].tolist())
    fp_by_strategy = Counter(false_positives["strategy"].tolist())
    fn_by_strategy = Counter(false_negatives["strategy"].tolist())

    return {
        "false_positives": {
            "count": len(false_positives),
            "by_sample_type": dict(fp_by_type),
            "by_strategy": dict(fp_by_strategy),
            "examples": sample_errors(false_positives),
        },
        "false_negatives": {
            "count": len(false_negatives),
            "by_sample_type": dict(fn_by_type),
            "by_strategy": dict(fn_by_strategy),
            "examples": sample_errors(false_negatives),
        },
    }


# ── Visualization ──────────────────────────────────────────────────────────────

def make_confusion_matrix_fig(metrics: dict, save_dir: Path, prefix: str) -> None:
    """
    Create and save confusion matrix heatmap (colorblind-friendly).
    Saves to both eval_dir and paper_fig_dir.
    """
    cm = np.array([
        [metrics["tn"], metrics["fp"]],
        [metrics["fn"], metrics["tp"]],
    ])

    fig, ax = plt.subplots(figsize=(4.5, 3.8))
    # Colorblind-friendly: blue palette
    cmap = sns.color_palette("Blues", as_cmap=True)
    sns.heatmap(
        cm, annot=True, fmt="d", cmap=cmap,
        xticklabels=["Predicted\nNegative", "Predicted\nPositive"],
        yticklabels=["Actual\nNegative", "Actual\nPositive"],
        linewidths=0.5, linecolor="gray",
        annot_kws={"size": 14, "weight": "bold"},
        ax=ax,
    )
    ax.set_title(
        f"SRR Rubric — Real Human Data\n"
        f"Acc={metrics['accuracy']:.3f}  P={metrics['precision']:.3f}  "
        f"R={metrics['recall']:.3f}  F1={metrics['f1']:.3f}",
        fontsize=10, pad=10,
    )
    ax.set_xlabel("Predicted Label", fontsize=10)
    ax.set_ylabel("True Label", fontsize=10)
    plt.tight_layout()

    for out_dir in [save_dir, PAPER_FIG_DIR]:
        png_path = out_dir / f"{prefix}_confusion_matrix.png"
        pdf_path = out_dir / f"{prefix}_confusion_matrix.pdf"
        fig.savefig(png_path, dpi=300, bbox_inches="tight")
        fig.savefig(pdf_path, bbox_inches="tight")
        print(f"  Saved: {png_path}")
        print(f"  Saved: {pdf_path}")

    plt.close(fig)


def make_strategy_bar_fig(metrics: dict, save_dir: Path, prefix: str) -> None:
    """
    Bar chart: detection rate (positive strategies) and false positive rate
    (negative strategies) per strategy.
    """
    sb = metrics["strategy_breakdown"]

    strategies = sorted(sb.keys())
    labels = []
    rates = []
    colors = []
    bar_type = []

    POSITIVE_COLOR = "#2166ac"   # Blue (colorblind-safe)
    NEGATIVE_COLOR = "#d6604d"   # Red-orange (colorblind-safe)

    for strat in strategies:
        info = sb[strat]
        if info["gold_label"] == "positive":
            # Detection rate = recall (how many true positives detected)
            rate = info["recall_or_detection_rate"]
            labels.append(f"{strat}\n(detect rate)")
            colors.append(POSITIVE_COLOR)
            bar_type.append("positive")
        else:
            # False positive rate for negative strategies
            rate = info["false_positive_rate"]
            labels.append(f"{strat}\n(FP rate)")
            colors.append(NEGATIVE_COLOR)
            bar_type.append("negative")
        rates.append(rate if rate is not None else 0.0)

    fig, ax = plt.subplots(figsize=(8, 4.5))
    x = np.arange(len(labels))
    bars = ax.bar(x, rates, color=colors, width=0.55, edgecolor="white", linewidth=0.5)

    # Annotate bars
    for bar, rate in zip(bars, rates):
        ax.text(
            bar.get_x() + bar.get_width() / 2,
            bar.get_height() + 0.02,
            f"{rate:.2f}",
            ha="center", va="bottom", fontsize=9, fontweight="bold",
        )

    ax.set_xticks(x)
    ax.set_xticklabels(labels, fontsize=8)
    ax.set_ylim(0, 1.15)
    ax.set_ylabel("Rate", fontsize=10)
    ax.set_title(
        "SRR Rubric: Detection Rate (positive strategies) and FP Rate (negative strategies)\n"
        "Data: Positive Psychology Frames, Ziems et al. ACL 2022 (CC BY-SA 4.0)",
        fontsize=9, pad=8,
    )
    ax.axhline(0.5, color="gray", linestyle="--", linewidth=0.8, alpha=0.5)

    # Legend
    legend_patches = [
        mpatches.Patch(color=POSITIVE_COLOR, label="Positive strategy (↑ higher = better)"),
        mpatches.Patch(color=NEGATIVE_COLOR, label="Negative strategy (↓ lower = better)"),
    ]
    ax.legend(handles=legend_patches, fontsize=8, loc="upper right")

    plt.tight_layout()

    for out_dir in [save_dir, PAPER_FIG_DIR]:
        png_path = out_dir / f"{prefix}_strategy_rates.png"
        pdf_path = out_dir / f"{prefix}_strategy_rates.pdf"
        fig.savefig(png_path, dpi=300, bbox_inches="tight")
        fig.savefig(pdf_path, bbox_inches="tight")
        print(f"  Saved: {png_path}")
        print(f"  Saved: {pdf_path}")

    plt.close(fig)


def make_sample_type_fig(metrics: dict, save_dir: Path, prefix: str) -> None:
    """
    Grouped bar: accuracy by sample type (positive / hard-neg / easy-neg).
    """
    tb = metrics["sample_type_breakdown"]
    types = ["positive", "hard_negative", "easy_negative"]
    labels_map = {
        "positive": "Positive\n(genuine reframe)",
        "hard_negative": "Hard Negative\n(neutralizing/impermanence)",
        "easy_negative": "Easy Negative\n(raw negative tweet)",
    }
    accs = [tb.get(t, {}).get("accuracy", 0.0) for t in types]
    ns = [tb.get(t, {}).get("n", 0) for t in types]
    colors_bar = ["#2166ac", "#f4a582", "#d6604d"]

    fig, ax = plt.subplots(figsize=(6, 4))
    x = np.arange(len(types))
    bars = ax.bar(x, accs, color=colors_bar, width=0.5, edgecolor="white")

    for bar, acc, n in zip(bars, accs, ns):
        ax.text(
            bar.get_x() + bar.get_width() / 2,
            bar.get_height() + 0.02,
            f"{acc:.2f}\n(n={n})",
            ha="center", va="bottom", fontsize=9,
        )

    ax.set_xticks(x)
    ax.set_xticklabels([labels_map[t] for t in types], fontsize=8)
    ax.set_ylim(0, 1.2)
    ax.set_ylabel("Accuracy", fontsize=10)
    ax.axhline(0.5, color="gray", linestyle="--", linewidth=0.8, alpha=0.5)
    ax.set_title(
        "SRR Rubric Accuracy by Sample Type\n"
        "Positive Psychology Frames, Ziems et al. ACL 2022 (CC BY-SA 4.0)",
        fontsize=9, pad=8,
    )
    plt.tight_layout()

    for out_dir in [save_dir, PAPER_FIG_DIR]:
        png_path = out_dir / f"{prefix}_sample_type_accuracy.png"
        pdf_path = out_dir / f"{prefix}_sample_type_accuracy.pdf"
        fig.savefig(png_path, dpi=300, bbox_inches="tight")
        fig.savefig(pdf_path, bbox_inches="tight")
        print(f"  Saved: {png_path}")
        print(f"  Saved: {pdf_path}")

    plt.close(fig)


# ── Save outputs ───────────────────────────────────────────────────────────────

def save_sample_csv(sample_df: pd.DataFrame) -> Path:
    path = RAW_DIR / "srr_realdata_sample_300.csv"
    sample_df.to_csv(path, index=False, encoding="utf-8")
    print(f"Sample CSV saved: {path}")
    return path


def save_results_csv(results_df: pd.DataFrame) -> Path:
    path = PROCESSED_DIR / "srr_realdata_results_300.csv"
    results_df.to_csv(path, index=False, encoding="utf-8")
    print(f"Results CSV saved: {path}")
    return path


def save_metrics_json(metrics: dict, error_analysis: dict) -> Path:
    output = {
        "meta": {
            "description": (
                "SRR Rubric Validation on Real Human Data — "
                "Positive Psychology Frames (Ziems et al., ACL 2022, CC BY-SA 4.0)"
            ),
            "dataset_citation": (
                "Ziems, C., Li, M., Zhang, A., & Yang, D. (2022). "
                "Inducing Positive Perspectives with Text Reframing. "
                "ACL 2022, 3682-3700. https://aclanthology.org/2022.acl-long.257/"
            ),
            "license": "CC BY-SA 4.0 (attribution required)",
            "generated_at": datetime.now(timezone.utc).isoformat(),
            "model": MODEL,
            "seed": SEED,
            "n_positive": N_POSITIVE,
            "n_negative_hard": N_NEGATIVE_HARD,
            "n_negative_easy": N_NEGATIVE_EASY,
            "n_total": N_TOTAL,
            "positive_strategies": sorted(POSITIVE_STRATEGIES),
            "hard_neg_strategies": sorted(HARD_NEG_STRATEGIES),
            "limitations": [
                "English-language data; GratiFlow targets Japanese users (cross-lingual gap).",
                "Ground truth derived from strategy labels, not independent SRR rubric annotation.",
                "neutralizing/impermanence as hard negatives is a design assumption, not verified by human raters.",
                "English few-shot examples in the rubric prompt may systematically advantage certain text styles.",
            ],
        },
        "metrics": metrics,
        "error_analysis": error_analysis,
    }
    path = PROCESSED_DIR / "srr_realdata_metrics.json"
    with open(path, "w", encoding="utf-8") as f:
        json.dump(output, f, ensure_ascii=False, indent=2)
    print(f"Metrics JSON saved: {path}")
    return path


# ── Entry point ────────────────────────────────────────────────────────────────

def main() -> None:
    print("=" * 70)
    print("GratiFlow SRR Rubric — Real Human Data Validation")
    print("Dataset: Positive Psychology Frames (Ziems et al., ACL 2022)")
    print("License: CC BY-SA 4.0 — Attribution required in all outputs")
    print("=" * 70)

    # Load API key
    print("\nLoading API key...")
    api_key = load_api_key()
    print("  API key loaded (not logged).")

    # Load dataset
    print("\nLoading dataset from HuggingFace: SALT-NLP/positive_reframing ...")
    ds = load_dataset("SALT-NLP/positive_reframing", trust_remote_code=True)
    ds_train = ds["train"]
    print(f"  Loaded {len(ds_train)} examples.")

    # Prepare sample
    sample_df = prepare_sample(ds_train)
    save_sample_csv(sample_df)

    # Run experiment
    results_df = run_experiment(api_key, sample_df)
    save_results_csv(results_df)

    # Compute metrics
    print("\nComputing metrics...")
    metrics = compute_metrics(results_df)
    error_analysis = analyze_errors(results_df)

    # Print summary
    print("\n" + "=" * 70)
    print("REAL-DATA VALIDATION RESULTS")
    print("=" * 70)
    print(f"  Dataset: Positive Psychology Frames (Ziems et al., ACL 2022, CC BY-SA 4.0)")
    print(f"  N={metrics['n_valid']} valid / {metrics['n_total']} total | Errors: {metrics['n_errors']}")
    print(f"  TP={metrics['tp']}, FP={metrics['fp']}, TN={metrics['tn']}, FN={metrics['fn']}")
    print(f"  Accuracy:  {metrics['accuracy']:.4f}")
    print(f"  Precision: {metrics['precision']:.4f}")
    print(f"  Recall:    {metrics['recall']:.4f}")
    print(f"  F1:        {metrics['f1']:.4f}")
    print("\nStrategy breakdown:")
    for strat, info in metrics["strategy_breakdown"].items():
        label = info["gold_label"]
        if label == "positive":
            print(f"  [{strat}] gold={label}, n={info['n']}, detect_rate={info['recall_or_detection_rate']}, acc={info['accuracy']}")
        else:
            print(f"  [{strat}] gold={label}, n={info['n']}, FP_rate={info['false_positive_rate']}, acc={info['accuracy']}")
    print("\nSample type breakdown:")
    for stype, info in metrics["sample_type_breakdown"].items():
        print(f"  [{stype}] n={info['n']}, acc={info['accuracy']}, FP={info['fp']}, FN={info['fn']}")
    print("\nError analysis:")
    print(f"  False Positives: {error_analysis['false_positives']['count']}")
    print(f"    by type: {error_analysis['false_positives']['by_sample_type']}")
    print(f"    by strategy: {error_analysis['false_positives']['by_strategy']}")
    print(f"  False Negatives: {error_analysis['false_negatives']['count']}")
    print(f"    by type: {error_analysis['false_negatives']['by_sample_type']}")
    print(f"    by strategy: {error_analysis['false_negatives']['by_strategy']}")
    print("=" * 70)

    # Save metrics
    save_metrics_json(metrics, error_analysis)

    # Figures
    FIGURE_PREFIX = "srr_realdata"
    print("\nGenerating figures...")
    make_confusion_matrix_fig(metrics, EVAL_DIR, FIGURE_PREFIX)
    make_strategy_bar_fig(metrics, EVAL_DIR, FIGURE_PREFIX)
    make_sample_type_fig(metrics, EVAL_DIR, FIGURE_PREFIX)

    print("\n" + "=" * 70)
    print("Validation complete. Results saved to:")
    print(f"  Raw sample CSV:  {RAW_DIR}/srr_realdata_sample_300.csv")
    print(f"  Results CSV:     {PROCESSED_DIR}/srr_realdata_results_300.csv")
    print(f"  Metrics JSON:    {PROCESSED_DIR}/srr_realdata_metrics.json")
    print(f"  Figures (eval):  {EVAL_DIR}/")
    print(f"  Figures (paper): {PAPER_FIG_DIR}/")
    print("=" * 70)


if __name__ == "__main__":
    main()
