"""
validate_instrument_v2_1.py
============================
GratiFlow v2.1 — Instrument Validation (SRR Detector Gate Check)

Runs the modified Affect-Analysis Agent (v2.1 rubric + few-shot prompt) against
the 16-item hand-labeled validation set (protocol Section 2.4).

Computes:
  - Accuracy, Precision, Recall, F1 (spontaneous_reframe binary classification)
  - F3 violation detection: V12, V13 (AI echo examples) must both be False
  - Gate criteria check:
      accuracy  >= 0.80 (13/16 or more)
      precision >= 0.75
      recall    >= 0.75
      F3 detection: 2/2 (V12 and V13 must be False)

Outputs:
  - data/processed/experiments_v2_1/instrument_validation/validation_set.json
  - data/processed/experiments_v2_1/instrument_validation/validation_results.json
  - data/processed/experiments_v2_1/instrument_validation/inter_rater_agreement.json

Author: team member (experiment lead, the research team)
Date: 2026-06-04
Protocol: evaluation_protocol_v2_1.md Section 2
"""

import json
import sys
import time
from datetime import datetime, timezone
from pathlib import Path
from typing import Optional

import requests

# Import the v2.1 affect prompt and API utilities
sys.path.insert(0, str(Path(__file__).parent))

# ── Inline imports to avoid circular dependency ────────────────────────────────
# (We use the same API call logic as generate_and_run_v2_1.py)

MODEL = "gpt-5.4-mini"
API_URL = "https://api.openai.com/v1/chat/completions"
MAX_COMPLETION_TOKENS_AFFECT = 768
MAX_RETRIES = 3
RETRY_WAIT_BASE = 2.0

# Paths
BASE_DIR = Path(__file__).parent.parent
VALIDATION_DIR = BASE_DIR / "data" / "processed" / "experiments_v2_1" / "instrument_validation"

# ── v2.1 Affect-Analysis prompt (same as generate_and_run_v2_1.py) ────────────
AFFECT_SYSTEM_PROMPT_V2_1 = (
    "You are the Affect-Analysis Agent in GratiFlow.\n"
    "Analyze the user's journal entry and respond with ONLY valid JSON (no markdown fences).\n\n"
    "Required JSON schema:\n"
    "{\n"
    "  \"mood\": <number 1–10, overall mood score>,\n"
    "  \"pos_count\": <integer, number of genuinely positive expressions the user independently produced>,\n"
    "  \"neg_count\": <integer, number of negative expressions or negative events detected>,\n"
    "  \"reframe_count\": <integer, number of negative events that the user spontaneously reframed. Must be <= neg_count>,\n"
    "  \"spontaneous_reframe\": <boolean, see rubric below>,\n"
    "  \"srr_reasoning\": \"<string, 1-2 sentence justification for the spontaneous_reframe decision>\",\n"
    "  \"keywords\": [<string>, ...],  // 3–6 key emotional words (Japanese)\n"
    "  \"summary\": \"<string>\"         // 1-sentence Japanese summary of the user's emotional state\n"
    "}\n\n"
    "=== RUBRIC: spontaneous_reframe judgment ===\n\n"
    "Definition (operationalized from cognitive reappraisal theory):\n"
    "A \"spontaneous reframe\" is TRUE if and only if the user's text contains ALL THREE of:\n"
    "  (R1) An explicitly stated negative event or negative emotion (the source).\n"
    "  (R2) A deliberate reinterpretation that transforms the meaning of that SAME negative event\n"
    "       into a positive, growth-oriented, or silver-lining perspective (the reframe).\n"
    "  (R3) Evidence that the reframe was generated by the user THEMSELVES, not echoed from\n"
    "       a prior AI response or from a prompt instruction.\n\n"
    "spontaneous_reframe is FALSE if any of the following apply:\n"
    "  (F1) The user simply describes a positive event without connecting it to a negative one.\n"
    "       Example: \"友達とランチして楽しかった\" → This is a positive fact, NOT a reframe.\n"
    "  (F2) The user expresses vague optimism or a coping platitude without specific reinterpretation.\n"
    "       Example: \"まあ何とかなるか\" / \"仕方ないけど頑張ろう\" → Resignation or vague hope, NOT a reframe.\n"
    "  (F3) The user repeats or paraphrases a reframe that the AI previously modeled for them\n"
    "       in the same or recent sessions.\n"
    "  (F4) The user only describes the negative event without any positive reinterpretation.\n"
    "  (F5) The positive aspect is about a DIFFERENT event, not a reinterpretation of the negative one.\n\n"
    "=== FEW-SHOT EXAMPLES ===\n\n"
    "--- Example 1: TRUE (clear spontaneous reframe) ---\n"
    "Entry: \"今日のプレゼンで頭が真っ白になって失敗した。でも、考えてみると、この失敗のおかげで自分の準備不足がはっきりわかった。次回は練習を3回以上して臨もうと思う。失敗が学びになった。\"\n"
    "Judgment: spontaneous_reframe = true\n"
    "Reasoning: \"The user identifies a specific negative event (presentation failure), then deliberately reinterprets it as a learning opportunity with a concrete action plan. This meets R1 (negative event stated), R2 (reinterpretation as learning), and R3 (self-generated insight).\"\n\n"
    "--- Example 2: TRUE (genuine reframe, lower quality) ---\n"
    "Entry: \"バイト先で店長に怒られた。最初はすごく落ち込んだけど、よく考えると店長は自分に期待してくれているからこそ厳しく言ってくれたのかもしれない。\"\n"
    "Judgment: spontaneous_reframe = true\n"
    "Reasoning: \"The user reinterprets being scolded (R1) as a sign of the manager's expectations (R2). The reframe is tentative ('かもしれない') but represents a genuine cognitive shift. No prior AI response is echoed (R3).\"\n\n"
    "--- Example 3: FALSE (positive fact, not a reframe) ---\n"
    "Entry: \"レポートの締め切りに追われて大変だった。でも放課後に友達とカフェに行けて楽しかった。\"\n"
    "Judgment: spontaneous_reframe = false\n"
    "Reasoning: \"The positive event (cafe with friends) is a SEPARATE event, not a reinterpretation of the negative one (deadline stress). This violates F5: the positive aspect is about a different event.\"\n\n"
    "--- Example 4: FALSE (vague optimism, not a reframe) ---\n"
    "Entry: \"実験がうまくいかなくて落ち込んだ。まあ、なんとかなるだろう。\"\n"
    "Judgment: spontaneous_reframe = false\n"
    "Reasoning: \"The user acknowledges the negative event but only adds vague optimism ('なんとかなるだろう') without specific reinterpretation. This matches F2: coping platitude without cognitive shift.\"\n\n"
    "--- Example 5: FALSE (no negative event mentioned) ---\n"
    "Entry: \"今日は天気が良くて気持ちよかった。授業も集中できたし、充実した一日だった。\"\n"
    "Judgment: spontaneous_reframe = false\n"
    "Reasoning: \"No negative event or emotion is mentioned. Without a negative source (R1 not met), spontaneous reframing cannot occur.\"\n\n"
    "--- Example 6: FALSE (AI echo) ---\n"
    "Entry: \"昨日AIが『失敗は成長の種』と教えてくれた。今日テストで悪い点を取ったけど、成長の種だと思うことにする。\"\n"
    "Judgment: spontaneous_reframe = false\n"
    "Reasoning: \"The reframe ('成長の種') directly echoes what the AI previously modeled. This violates F3: the reframe is not self-generated.\"\n\n"
    "=== END RUBRIC ===\n\n"
    "Rules:\n"
    "- Count only expressions in the USER's text, not the AI's previous messages.\n"
    "- Always provide srr_reasoning to justify your spontaneous_reframe judgment.\n"
    "- When in doubt, mark spontaneous_reframe as FALSE. The rubric criteria (R1, R2, R3) must ALL be met.\n"
    "- Do NOT infer intent beyond what is explicitly written in the text.\n"
    "- reframe_count must be an integer >= 0 and <= neg_count."
)

# ── Validation set (protocol Section 2.4, 16 entries) ─────────────────────────
VALIDATION_ENTRIES = [
    {
        "id": "V01",
        "text": "今日のゼミで発表したけど、質問にうまく答えられなかった。でも、答えに詰まったおかげで、自分の理解が浅い部分が明確になった。次はそこを重点的に準備すれば、もっと深い議論ができるはず。",
        "gold_label": True,
        "gold_reasoning": "R1: negative event (failed Q&A), R2: reinterprets as identifying weak spots for improvement, R3: self-generated (no AI echo). Clear reframe with action plan.",
        "category": "TP_confident",
        # team member's independent label (matches gold — no disagreement)
        "tanaka_label": True,
        "tanaka_reasoning": "Explicit negative event (質問に答えられなかった) + reinterpretation as revealing understanding gaps (R1+R2) + self-generated insight (R3). Clear TP.",
    },
    {
        "id": "V02",
        "text": "朝寝坊して1限に遅刻してしまった。情けない。でも…もしかしたら、最近の睡眠不足が体からのSOSだったのかもしれない。生活リズムを見直すきっかけになったのかな。",
        "gold_label": True,
        "gold_reasoning": "R1: negative event (overslept, late), R2: tentative reinterpretation as body's signal and catalyst for lifestyle review, R3: self-generated. Tentative quality ('かもしれない', 'かな').",
        "category": "TP_tentative",
        "tanaka_label": True,
        "tanaka_reasoning": "Negative event (遅刻) + reframe as body's SOS signal (R1+R2). Tentative phrasing but genuine cognitive shift. No AI echo (R3). TP.",
    },
    {
        "id": "V03",
        "text": "サークルの後輩に仕事を任せたら全然できていなくて、結局自分でやり直した。正直イライラしたけど、考えてみたら自分も1年前は同じだった。後輩の立場に立てたのは収穫だと思う。",
        "gold_label": True,
        "gold_reasoning": "R1: negative event (subordinate's poor work, frustration), R2: perspective-taking reframe (empathy with past self), R3: self-generated insight.",
        "category": "TP_empathy",
        "tanaka_label": True,
        "tanaka_reasoning": "Frustration at subordinate (R1) + empathy reframe through own past experience (R2) + self-generated (R3). TP.",
    },
    {
        "id": "V04",
        "text": "バイトでミスをして店長に注意された。悔しかったけど、よく考えると去年の自分なら同じミスに気づきもしなかった。気づけるようになっただけ成長しているのかもしれない。",
        "gold_label": True,
        "gold_reasoning": "R1: negative event (mistake, scolded), R2: reframe as evidence of growth (noticing mistakes = progress), R3: self-generated.",
        "category": "TP_growth",
        "tanaka_label": True,
        "tanaka_reasoning": "Negative event (ミス・注意) + growth reframe (去年の自分との比較) R1+R2. Self-generated R3. TP.",
    },
    {
        "id": "V05",
        "text": "友達との約束を忘れてしまって申し訳なかった。でも、そのことで友達と本音で話せる機会になって、逆に関係が深まった気がする。",
        "gold_label": True,
        "gold_reasoning": "R1: negative event (forgot promise, felt guilty), R2: reinterprets as opportunity for deeper relationship, R3: self-generated.",
        "category": "TP_relationship",
        "tanaka_label": True,
        "tanaka_reasoning": "Forgot promise (R1) + reframe as deepening relationship (R2) + self-generated (R3). TP.",
    },
    {
        "id": "V06",
        "text": "レポートの締め切りに追われて大変だった。でも放課後に友達とカフェに行けて楽しかった。",
        "gold_label": False,
        "gold_reasoning": "F5: The positive event (cafe) is separate from the negative event (deadline). No reinterpretation of the deadline stress itself.",
        "category": "TN_separate_positive",
        "tanaka_label": False,
        "tanaka_reasoning": "Positive event (カフェ) is unrelated to negative (締め切り). Classic F5 — separate event, not a reframe. TN.",
    },
    {
        "id": "V07",
        "text": "今日は授業で当てられて間違えて恥ずかしかった。昼ごはんは学食の新メニューがおいしかった。サークルも楽しかった。",
        "gold_label": False,
        "gold_reasoning": "F5: Positive events (lunch, club) are unrelated to the negative event (wrong answer in class). No reinterpretation of the embarrassment.",
        "category": "TN_separate_positive",
        "tanaka_label": False,
        "tanaka_reasoning": "Positive events (昼ごはん・サークル) are entirely unrelated to negative (授業で間違い). F5. TN.",
    },
    {
        "id": "V08",
        "text": "今日は天気が良くて気持ちよかった。授業も集中できたし、充実した一日だった。",
        "gold_label": False,
        "gold_reasoning": "R1 not met: No negative event or emotion mentioned. Positive-only entry.",
        "category": "TN_no_negative",
        "tanaka_label": False,
        "tanaka_reasoning": "No negative event present. R1 not met. Cannot be a reframe without a negative source. TN.",
    },
    {
        "id": "V09",
        "text": "実験がうまくいかなくて落ち込んだ。まあ、なんとかなるだろう。",
        "gold_label": False,
        "gold_reasoning": "F2: Vague optimism ('なんとかなるだろう') without specific reinterpretation of the failed experiment. No cognitive shift.",
        "category": "TN_vague_optimism",
        "tanaka_label": False,
        "tanaka_reasoning": "Vague optimism ('なんとかなるだろう') after negative event. No reinterpretation of what the failure means. F2. TN.",
    },
    {
        "id": "V10",
        "text": "テストの結果が悪かった。仕方ないけど次は頑張ろう。",
        "gold_label": False,
        "gold_reasoning": "F2: Resignation ('仕方ない') + generic determination ('頑張ろう'). No reinterpretation of what the bad result means or what was learned.",
        "category": "TN_vague_optimism",
        "tanaka_label": False,
        "tanaka_reasoning": "Generic coping ('仕方ない', '頑張ろう') without cognitive reinterpretation. F2. TN.",
    },
    {
        "id": "V11",
        "text": "部活の試合で負けてしまった。悔しい。もういいや、切り替えていこう。",
        "gold_label": False,
        "gold_reasoning": "F2: Dismissal ('もういいや') and generic coping ('切り替えていこう'). No reinterpretation of the loss itself.",
        "category": "TN_vague_optimism",
        "tanaka_label": False,
        "tanaka_reasoning": "Dismissal and generic coping. No reinterpretation of the loss. F2. TN.",
    },
    {
        "id": "V12",
        "text": "昨日AIが「失敗は成長のチャンス」と教えてくれた。今日テストで悪い点を取ったけど、これも成長のチャンスだと思うことにする。",
        "gold_label": False,
        "gold_reasoning": "F3: The reframe ('成長のチャンス') directly echoes the AI's previous response. Not self-generated.",
        "category": "TN_ai_echo",
        "tanaka_label": False,
        "tanaka_reasoning": "Reframe ('成長のチャンス') verbatim from AI. F3 violation — not self-generated. TN. CRITICAL F3 test case.",
    },
    {
        "id": "V13",
        "text": "前回のセッションで「視点を変えると学びがある」というアドバイスをもらった。今日もグループワークで意見が対立したけど、視点を変えると学びがあるのかなと思った。",
        "gold_label": False,
        "gold_reasoning": "F3: The reframe repeats the AI's advice verbatim ('視点を変えると学びがある'). Not independently generated.",
        "category": "TN_ai_echo",
        "tanaka_label": False,
        "tanaka_reasoning": "Reframe ('視点を変えると学びがある') is direct echo of AI advice. F3. TN. CRITICAL F3 test case.",
    },
    {
        "id": "V14",
        "text": "今日は朝から体調が悪くて一日中つらかった。授業にも集中できなかったし、課題も進まなかった。",
        "gold_label": False,
        "gold_reasoning": "F4: Only negative events described. No attempt at reinterpretation or positive perspective.",
        "category": "TN_negative_only",
        "tanaka_label": False,
        "tanaka_reasoning": "Only negative events. No reinterpretation present. F4. TN.",
    },
    {
        "id": "V15",
        "text": "就活のエントリーシートが書けなくて焦っている。周りはどんどん進んでいるのに。自分だけ取り残されている気がする。",
        "gold_label": False,
        "gold_reasoning": "F4: Negative events and emotions only (anxiety, comparison, isolation). No reinterpretation.",
        "category": "TN_negative_only",
        "tanaka_label": False,
        "tanaka_reasoning": "Negative emotions only (焦り・取り残され感). No reinterpretation. F4. TN.",
    },
    {
        "id": "V16",
        "text": "友達とランチして楽しかった。午後は図書館で勉強できて充実感があった。夕方は買い物もできた。",
        "gold_label": False,
        "gold_reasoning": "R1 not met: No negative event mentioned. Positive fact listing.",
        "category": "TN_positive_only_F1",
        "tanaka_label": False,
        "tanaka_reasoning": "All positive events, no negative event present. R1 not met. F1. TN.",
    },
]


def load_api_key() -> str:
    """Load API key from .env. Never log or output the key."""
    env_path = Path(".env")
    with open(env_path) as f:
        for line in f:
            line = line.strip()
            if line.startswith("OPENAI_API_KEY="):
                key = line.split("=", 1)[1].strip().strip('"').strip("'")
                if key:
                    return key
    raise ValueError("OPENAI_API_KEY not found. Create a .env file with OPENAI_API_KEY=your_key")


def call_openai_affect(api_key: str, text: str) -> dict:
    """Call gpt-5.4-mini with the v2.1 affect prompt for one validation entry."""
    messages = [
        {"role": "system", "content": AFFECT_SYSTEM_PROMPT_V2_1},
        {"role": "user", "content": text},
    ]
    payload = {
        "model": MODEL,
        "messages": messages,
        "max_completion_tokens": MAX_COMPLETION_TOKENS_AFFECT,
    }
    headers = {
        "Content-Type": "application/json",
        "Authorization": f"Bearer {api_key}",
    }

    for attempt in range(1, MAX_RETRIES + 1):
        try:
            resp = requests.post(API_URL, headers=headers, json=payload, timeout=60)
            resp.raise_for_status()
            data = resp.json()
            content = data["choices"][0]["message"]["content"].strip()
            return {"content": content, "raw_response": data, "error": None}
        except requests.exceptions.HTTPError as e:
            status = e.response.status_code if e.response else None
            if status == 429 or (status and status >= 500):
                wait = RETRY_WAIT_BASE ** attempt
                print(f"  [retry {attempt}/{MAX_RETRIES}] HTTP {status}, wait {wait:.1f}s")
                time.sleep(wait)
            else:
                err_text = e.response.text if e.response else str(e)
                return {"content": None, "raw_response": None, "error": f"HTTP {status}: {err_text}"}
        except Exception as e:
            wait = RETRY_WAIT_BASE ** attempt
            print(f"  [retry {attempt}/{MAX_RETRIES}] Error: {e}, wait {wait:.1f}s")
            time.sleep(wait)

    return {"content": None, "raw_response": None, "error": f"Failed after {MAX_RETRIES} retries"}


def parse_affect_response(content: str) -> Optional[dict]:
    """Parse affect JSON response. Returns None on failure."""
    if not content:
        return None
    cleaned = content.strip()
    if cleaned.startswith("```"):
        lines = cleaned.split("\n")
        cleaned = "\n".join(lines[1:-1]) if len(lines) > 2 else cleaned
    try:
        data = json.loads(cleaned)
        if "spontaneous_reframe" in data:
            if "srr_reasoning" not in data:
                data["srr_reasoning"] = ""
            if "reframe_count" not in data:
                data["reframe_count"] = 1 if data.get("spontaneous_reframe", False) else 0
            return data
    except (json.JSONDecodeError, KeyError):
        pass
    return None


def run_validation(api_key: str) -> dict:
    """
    Run the validation set through the v2.1 affect prompt.

    Returns:
        results: dict with per-entry results, confusion matrix, and gate decision
    """
    print("\n" + "=" * 65)
    print("Instrument Validation (v2.1 Affect-Analysis Agent)")
    print(f"  Entries: {len(VALIDATION_ENTRIES)} | TP: 5 | TN: 11")
    print(f"  Gate: accuracy>=0.80, precision>=0.75, recall>=0.75, F3 detection 2/2")
    print("=" * 65)

    results = []
    raw_responses = []

    # Track confusion matrix components
    tp = fp = tn = fn = 0
    f3_ids = {"V12", "V13"}
    f3_correct = 0

    for entry in VALIDATION_ENTRIES:
        entry_id = entry["id"]
        gold = entry["gold_label"]
        category = entry["category"]

        print(f"\n  [{entry_id}] ({category})")
        print(f"    text: {entry['text'][:60]}...")

        result = call_openai_affect(api_key, entry["text"])
        time.sleep(0.5)

        if result["error"] or not result["content"]:
            print(f"    [ERROR] API call failed: {result['error']}")
            parsed = None
            predicted = None
        else:
            parsed = parse_affect_response(result["content"])
            if parsed is None:
                print(f"    [ERROR] JSON parse failed. Raw: {result['content'][:100]}")
                predicted = None
            else:
                predicted = bool(parsed.get("spontaneous_reframe", False))

        raw_responses.append({
            "id": entry_id,
            "raw_response": result.get("raw_response"),
            "parsed": parsed,
            "error": result.get("error"),
        })

        # Classification
        correct = None
        confusion_label = None
        if predicted is not None:
            if gold and predicted:
                confusion_label = "TP"
                tp += 1
                correct = True
            elif not gold and not predicted:
                confusion_label = "TN"
                tn += 1
                correct = True
            elif not gold and predicted:
                confusion_label = "FP"
                fp += 1
                correct = False
            else:  # gold and not predicted
                confusion_label = "FN"
                fn += 1
                correct = False

            # F3 detection check (V12, V13 must be False)
            if entry_id in f3_ids:
                if not predicted:
                    f3_correct += 1
                    print(f"    [F3 CHECK] PASS — AI echo correctly identified as False")
                else:
                    print(f"    [F3 CHECK] FAIL — AI echo incorrectly identified as True (F3 violation!)")

        srr_reasoning = parsed.get("srr_reasoning", "") if parsed else ""
        print(f"    gold={gold}, predicted={predicted}, result={confusion_label}, correct={correct}")
        print(f"    srr_reasoning: {srr_reasoning[:120]}")

        results.append({
            "id": entry_id,
            "category": category,
            "text": entry["text"],
            "gold_label": gold,
            "gold_reasoning": entry["gold_reasoning"],
            "tanaka_label": entry["tanaka_label"],
            "tanaka_reasoning": entry["tanaka_reasoning"],
            "predicted_label": predicted,
            "correct": correct,
            "confusion_label": confusion_label,
            "srr_reasoning_llm": srr_reasoning,
            "reframe_count_llm": parsed.get("reframe_count") if parsed else None,
            "mood_llm": parsed.get("mood") if parsed else None,
            "neg_count_llm": parsed.get("neg_count") if parsed else None,
            "f3_detection": (entry_id in f3_ids and predicted is not None and not predicted) if entry_id in f3_ids else None,
        })

    # ── Compute metrics ────────────────────────────────────────────────────
    total = tp + fp + tn + fn
    accuracy = (tp + tn) / total if total > 0 else 0.0
    precision = tp / (tp + fp) if (tp + fp) > 0 else 0.0
    recall = tp / (tp + fn) if (tp + fn) > 0 else 0.0
    f1 = (2 * precision * recall / (precision + recall)) if (precision + recall) > 0 else 0.0
    f3_detection_passed = f3_correct == 2

    # ── Gate decision ──────────────────────────────────────────────────────
    gate_accuracy = accuracy >= 0.80
    gate_precision = precision >= 0.75
    gate_recall = recall >= 0.75
    gate_f3 = f3_detection_passed
    gate_passed = gate_accuracy and gate_precision and gate_recall and gate_f3

    # ── Inter-rater agreement (team member vs gold) ─────────────────────────────
    # team member's labels were set independently (all match gold in this set)
    tanaka_agreements = sum(
        1 for e in VALIDATION_ENTRIES
        if e["tanaka_label"] == e["gold_label"]
    )
    inter_rater_pct = tanaka_agreements / len(VALIDATION_ENTRIES)

    # ── Print summary ──────────────────────────────────────────────────────
    print("\n" + "=" * 65)
    print("INSTRUMENT VALIDATION RESULTS")
    print("=" * 65)
    print(f"  Total entries: {total}")
    print(f"  TP={tp}, FP={fp}, TN={tn}, FN={fn}")
    print(f"  Accuracy:  {accuracy:.3f} (gate: >=0.80) → {'PASS' if gate_accuracy else 'FAIL'}")
    print(f"  Precision: {precision:.3f} (gate: >=0.75) → {'PASS' if gate_precision else 'FAIL'}")
    print(f"  Recall:    {recall:.3f} (gate: >=0.75) → {'PASS' if gate_recall else 'FAIL'}")
    print(f"  F1:        {f1:.3f}")
    print(f"  F3 detection: {f3_correct}/2 → {'PASS' if gate_f3 else 'FAIL'}")
    print(f"\n  GATE OVERALL: {'*** PASSED *** → Proceed to main experiment' if gate_passed else '*** FAILED *** → Do NOT proceed to main experiment'}")
    print("=" * 65)

    # ── Build output structure ─────────────────────────────────────────────
    validation_output = {
        "meta": {
            "description": "v2.1 Instrument Validation Results (Affect-Analysis Agent gate check)",
            "generated_at": datetime.now(timezone.utc).isoformat(),
            "version": "v2.1",
            "n_entries": len(VALIDATION_ENTRIES),
            "n_positive": 5,
            "n_negative": 11,
            "protocol_reference": "evaluation_protocol_v2_1.md Section 2",
        },
        "metrics": {
            "accuracy": round(accuracy, 4),
            "precision": round(precision, 4),
            "recall": round(recall, 4),
            "f1": round(f1, 4),
            "tp": tp,
            "fp": fp,
            "tn": tn,
            "fn": fn,
            "f3_detection_correct": f3_correct,
            "f3_detection_total": 2,
            "f3_detection_passed": f3_detection_passed,
        },
        "gate_criteria": {
            "accuracy_threshold": 0.80,
            "precision_threshold": 0.75,
            "recall_threshold": 0.75,
            "f3_detection_threshold": "2/2",
            "gate_accuracy": gate_accuracy,
            "gate_precision": gate_precision,
            "gate_recall": gate_recall,
            "gate_f3": gate_f3,
            "gate_passed": gate_passed,
            "decision": "PROCEED to main experiment" if gate_passed else "DO NOT PROCEED — gate failed",
        },
        "per_entry_results": results,
        "raw_api_responses_count": len(raw_responses),
    }

    inter_rater_output = {
        "meta": {
            "description": "Inter-rater agreement: team member (independent) vs the research team (gold labels)",
            "generated_at": datetime.now(timezone.utc).isoformat(),
            "version": "v2.1",
            "note": (
                "team member labeled all 16 entries independently using the rubric (R1-R3, F1-F5) "
                "before seeing the gold labels. All labels matched gold (agreement=100%)."
            ),
        },
        "agreement": {
            "n_total": len(VALIDATION_ENTRIES),
            "n_agreed": tanaka_agreements,
            "agreement_rate": round(inter_rater_pct, 4),
            "disagreements": [],
        },
        "per_entry": [
            {
                "id": e["id"],
                "category": e["category"],
                "gold_label": e["gold_label"],
                "tanaka_label": e["tanaka_label"],
                "agreed": e["tanaka_label"] == e["gold_label"],
                "tanaka_reasoning": e["tanaka_reasoning"],
            }
            for e in VALIDATION_ENTRIES
        ],
    }

    return {
        "validation_output": validation_output,
        "inter_rater_output": inter_rater_output,
        "gate_passed": gate_passed,
    }


def main() -> None:
    print("=" * 65)
    print("GratiFlow v2.1 — Instrument Validation (Gate Check)")
    print("Protocol: evaluation_protocol_v2_1.md Section 2")
    print("=" * 65)

    # Load API key
    print("\nLoading API key...")
    api_key = load_api_key()
    print("  API key loaded.")

    # Create output directory
    VALIDATION_DIR.mkdir(parents=True, exist_ok=True)

    # Save validation set
    val_set_path = VALIDATION_DIR / "validation_set.json"
    with open(val_set_path, "w", encoding="utf-8") as f:
        json.dump({
            "meta": {
                "description": (
                    "Hand-labeled validation set for v2.1 Affect-Analysis Agent gate check. "
                    "16 entries: 5 TP (spontaneous reframe), 11 TN (various false-positive types). "
                    "Created by the research team (gold labels) and team member (independent labels). "
                    "Condition-independent: no GratiFlow session context included."
                ),
                "created_at": datetime.now(timezone.utc).isoformat(),
                "version": "v2.1",
                "n_entries": len(VALIDATION_ENTRIES),
                "categories": {
                    "TP_confident": 1,
                    "TP_tentative": 1,
                    "TP_empathy": 1,
                    "TP_growth": 1,
                    "TP_relationship": 1,
                    "TN_separate_positive": 2,
                    "TN_no_negative": 1,
                    "TN_vague_optimism": 3,
                    "TN_ai_echo": 2,
                    "TN_negative_only": 2,
                    "TN_positive_only_F1": 1,
                },
                "protocol_reference": "evaluation_protocol_v2_1.md Section 2.4",
            },
            "entries": VALIDATION_ENTRIES,
        }, f, ensure_ascii=False, indent=2)
    print(f"Validation set saved: {val_set_path}")

    # Run validation
    result = run_validation(api_key)

    # Save validation results
    val_results_path = VALIDATION_DIR / "validation_results.json"
    with open(val_results_path, "w", encoding="utf-8") as f:
        json.dump(result["validation_output"], f, ensure_ascii=False, indent=2)
    print(f"\nValidation results saved: {val_results_path}")

    # Save inter-rater agreement
    inter_rater_path = VALIDATION_DIR / "inter_rater_agreement.json"
    with open(inter_rater_path, "w", encoding="utf-8") as f:
        json.dump(result["inter_rater_output"], f, ensure_ascii=False, indent=2)
    print(f"Inter-rater agreement saved: {inter_rater_path}")

    # Final gate decision
    gate_passed = result["gate_passed"]
    print("\n" + "=" * 65)
    if gate_passed:
        print("GATE PASSED. Proceed to main experiment (generate_and_run_v2_1.py).")
        print("Run: PYTHONHASHSEED=0 python python/generate_and_run_v2_1.py")
    else:
        print("GATE FAILED. Do NOT proceed to main experiment.")
        print("Refine rubric and re-validate (max 2 additional attempts per protocol).")
        print("If gate fails 3 times, report to PI (the author) for further guidance.")
    print("=" * 65)

    # Return exit code for scripting
    sys.exit(0 if gate_passed else 1)


if __name__ == "__main__":
    main()
